### PR TITLE
Authentication v1

### LINKED ISSUE #15: Get authentification

### PR DESCRIPTION
**Pull request by isimic95**
Close #15

### CODE REVIEW

**Comment by HealYouDown** [comment]
Looks good to me.

Hoewever, I would like to somehow include the location data for the user on the registration. This could be done via two hidden fields, one for longitude and one for latidude. This would allow us to show content on the first dashboard rendering, instead of then having to ask for permissions and reload the page again.
Is that possible? I think we would just have to check in the backend if both fields are present.

~We would also need a more customized user model, as it needs to save the longitude and the latidude as well.~

Another thing I would like to point out is that I'm not sure if we need a profile page. We could display a dropdown on the dashboard with the option to reset the email / password, if that is needed. I think it is enough if you see two links on the login page to do so.
Or did you have another plan what to display on the `account/profile` page?

**Comment by maxrdu** [comment]
I tried opening the urls you added @isimic95, however all return Page not found maybe there is some misconfiguration with the url settings or templates?

**Comment by HealYouDown** [comment]
> 
> 
> I tried opening the urls you added @isimic95, however all return Page not found maybe there is some misconfiguration with the url settings or templates?

They work for me. Only some templates can't be loaded as there is no base.html, which will be fixed once it is merged, as we will combine it with the base.html from the dashboard app.

**Comment by maxrdu** [comment]
After trying again you are right. Login and Register views are working fine

**Comment by maxrdu** [comment]
Actually we dont need a customized user model but can just use proxy models as shown in the docs [extending the user model.](https://docs.djangoproject.com/en/3.0/topics/auth/customizing/#extending-user)

**Comment by HealYouDown** [comment]
I now removed all unnecessary urls.

Because we do not have a lot of time left, I just added basic login/logout and register function. No password reset or anything else.

**Review by maxrdu — APPROVED** [review]

**Pull request merged**
